"""Regression tests for the morphology contract implemented by REMOD.

The synthetic fixtures have analytically tractable topology and geometry.  The
bundled morphology assertions are independent reference values, rather than
snapshots generated by the implementation under test.
"""

from __future__ import annotations

from collections import Counter
from contextlib import redirect_stdout
from io import StringIO
import importlib.util
import json
from math import pi, sqrt
from pathlib import Path
import random
import subprocess
import sys
import tempfile
import unittest

import numpy as np

from core_utils import sample_random_dendrites
from file_io import write_json
from json_stats import compute_statistics, main as json_main
from morphology_statistics import (
    sholl_branch_points,
    sholl_intersections,
    sholl_length,
)
from remodeling_actions import execute_action, parse_length_distribution, select_length
from swc_parser import (
    dendrite_volumes,
    parse_swc_file,
    parse_swc_lines,
    validate_samples,
)


REPOSITORY = Path(__file__).resolve().parent
BUNDLED_MORPHOLOGY = REPOSITORY / "swc_files" / "0-2.CNG.swc"
SECOND_BUNDLED_MORPHOLOGY = REPOSITORY / "swc_files" / "0-2a.CNG.swc"

# Indices in the compatibility tuple returned by parse_swc_file.
SAMPLES = 1
BRANCH_POINTS = 3
SOMA_SAMPLES = 8
MAX_SAMPLE_ID = 9
DENDRITE_ROOTS = 10
DESCENDANTS = 11
SAMPLE_IDS_BY_SEGMENT = 12
BASAL = 15
APICAL = 16
DENDRITE_SAMPLES = 18
SOMA_PATHS = 19
TERMINALS = 20
BASAL_TERMINALS = 21
APICAL_TERMINALS = 22
LENGTHS = 23
AREAS = 24
BRANCH_ORDER = 25
PARENTS = 27


Y_MORPHOLOGY = """\
# Analytic two-region morphology
1 1 0 0 0 0.5 -1
2 3 1 0 0 0.5 1
3 3 2 0 0 0.5 2
4 3 3 1 0 0.5 3
5 3 3 -1 0 0.5 3
6 4 0 1 0 0.5 1
7 4 0 2 0 0.5 6
"""


CHORD_MORPHOLOGY = """\
1 1 0 0 0 0.5 -1
2 3 15 0 0 0.5 1
3 3 -15 0 0 0.5 2
"""


UNBRANCHED_MORPHOLOGY = """\
1 1 0 0 0 0.5 -1
2 3 5 0 0 0.5 1
"""


def parse_text(text: str):
    """Parse an in-memory fixture through the public file parser."""

    with tempfile.TemporaryDirectory() as directory:
        path = Path(directory) / "fixture.swc"
        path.write_text(text, encoding="utf-8")
        return parse_swc_file(path)


def statistics_for_text(text: str):
    """Compute statistics for an in-memory fixture."""

    with tempfile.TemporaryDirectory() as directory:
        path = Path(directory) / "fixture.swc"
        path.write_text(text, encoding="utf-8")
        return compute_statistics(path)


def total_dendritic_length(parsed) -> float:
    return sum(parsed[LENGTHS][root] for root in parsed[DENDRITE_ROOTS])


def total_dendritic_volume(parsed) -> float:
    volumes = dendrite_volumes(
        parsed[DENDRITE_SAMPLES],
        parsed[DENDRITE_ROOTS],
        parsed[PARENTS],
        parsed[SAMPLES],
    )
    return sum(volumes.values())


def remodel(
    morphology: str,
    targets,
    action: str,
    amount=None,
    extent_unit: str = "percent",
    radius_change=None,
    radius_unit: str = "percent",
    seed: int = 17,
):
    """Run an action on a fresh fixture and reparse its serialized result."""

    before = parse_text(morphology)
    working = parse_text(morphology)
    lines = execute_action(
        targets,
        action,
        amount,
        extent_unit,
        working[DENDRITE_SAMPLES],
        working[LENGTHS],
        radius_change,
        working[SOMA_SAMPLES],
        working[DESCENDANTS],
        radius_unit=radius_unit,
        seed=seed,
    )
    _comments, serialized_samples = parse_swc_lines(lines)
    validate_samples(serialized_samples)
    after = parse_text("\n".join(lines) + "\n")
    return before, after, lines, after[DENDRITE_ROOTS], []


class StrictSWCParsingTests(unittest.TestCase):
    def test_comments_blanks_and_valid_rows_are_parsed(self):
        comments, samples = parse_swc_lines(
            ["# source", "", "1 1 0 0 0 1 -1", "2 3 1 0 0 0.5 1"]
        )
        validate_samples(samples)
        self.assertEqual(comments, ["# source"])
        self.assertEqual(set(samples), {1, 2})

    def test_malformed_rows_and_values_are_rejected(self):
        cases = {
            "too few columns": ["1 1 0 0 0 1"],
            "too many columns": ["1 1 0 0 0 1 -1 extra"],
            "non-integer identifier": ["one 1 0 0 0 1 -1"],
            "non-positive identifier": ["0 1 0 0 0 1 -1"],
            "non-finite coordinate": ["1 1 nan 0 0 1 -1"],
            "zero radius": ["1 1 0 0 0 0 -1"],
            "negative radius": ["1 1 0 0 0 -0.1 -1"],
            "duplicate identifier": [
                "1 1 0 0 0 1 -1",
                "1 3 1 0 0 0.5 1",
            ],
        }
        for label, lines in cases.items():
            with self.subTest(label=label), self.assertRaises(ValueError):
                parse_swc_lines(lines)

    def test_invalid_topologies_are_rejected(self):
        cases = {
            "missing parent": [
                "1 1 0 0 0 1 -1",
                "2 3 1 0 0 0.5 99",
            ],
            "self parent": [
                "1 1 0 0 0 1 -1",
                "2 3 1 0 0 0.5 2",
            ],
            "no root": [
                "1 1 0 0 0 1 2",
                "2 3 1 0 0 0.5 1",
            ],
            "non-soma root": [
                "1 1 0 0 0 1 -1",
                "2 3 1 0 0 0.5 -1",
            ],
            "multiple soma roots": [
                "1 1 0 0 0 1 -1",
                "2 1 1 0 0 1 -1",
            ],
            "cycle": [
                "1 1 0 0 0 1 -1",
                "2 3 1 0 0 0.5 3",
                "3 3 2 0 0 0.5 2",
            ],
        }
        for label, lines in cases.items():
            with self.subTest(label=label):
                _comments, samples = parse_swc_lines(lines)
                with self.assertRaises(ValueError):
                    validate_samples(samples)


class SegmentTopologyAndGeometryTests(unittest.TestCase):
    def setUp(self):
        self.parsed = parse_text(Y_MORPHOLOGY)

    def test_segments_begin_after_soma_or_bifurcation(self):
        parsed = self.parsed
        self.assertEqual(parsed[DENDRITE_ROOTS], [2, 4, 5, 6])
        self.assertEqual(
            parsed[SAMPLE_IDS_BY_SEGMENT],
            {2: [2, 3], 4: [4], 5: [5], 6: [6, 7]},
        )
        self.assertEqual(parsed[BRANCH_POINTS], [3])
        self.assertEqual(parsed[SOMA_PATHS], {2: [2], 4: [4, 2], 5: [5, 2], 6: [6]})
        self.assertEqual(parsed[DESCENDANTS], {2: [4, 5], 4: [], 5: [], 6: []})
        self.assertEqual(parsed[TERMINALS], [4, 5, 6])
        self.assertEqual(parsed[BASAL_TERMINALS], [4, 5])
        self.assertEqual(parsed[APICAL_TERMINALS], [6])
        self.assertEqual(parsed[BRANCH_ORDER], {2: 1, 4: 2, 5: 2, 6: 1})

    def test_lengths_areas_and_volumes_match_closed_form_values(self):
        parsed = self.parsed
        expected_total_length = 4.0 + 2.0 * sqrt(2.0)
        self.assertAlmostEqual(total_dendritic_length(parsed), expected_total_length)
        self.assertAlmostEqual(sum(parsed[AREAS].values()), pi * expected_total_length)
        self.assertAlmostEqual(
            total_dendritic_volume(parsed), pi * expected_total_length / 4.0
        )

    def test_numeric_overflow_is_rejected(self):
        morphology = """\
1 1 -1e308 0 0 1 -1
2 3 1e308 0 0 0.5 1
"""
        with self.assertRaisesRegex(ValueError, "finite numeric range"):
            parse_text(morphology)

    def test_area_and_volume_use_the_distal_sample_radius(self):
        morphology = """\
1 1 0 0 0 10 -1
2 3 2 0 0 1 1
3 3 5 0 0 2 2
"""
        parsed = parse_text(morphology)
        self.assertAlmostEqual(sum(parsed[AREAS].values()), 16.0 * pi)
        self.assertAlmostEqual(total_dendritic_volume(parsed), 14.0 * pi)

    def test_type_change_starts_a_segment_without_incrementing_branch_order(self):
        morphology = """\
1 1 0 0 0 1 -1
2 3 1 0 0 0.5 1
3 4 2 0 0 0.5 2
4 4 3 0 0 0.5 3
"""
        parsed = parse_text(morphology)
        self.assertEqual(parsed[DENDRITE_ROOTS], [2, 3])
        self.assertEqual(parsed[BRANCH_POINTS], [])
        self.assertEqual(parsed[BRANCH_ORDER], {2: 1, 3: 1})

    def test_diameter_and_taper_conventions_have_analytic_values(self):
        morphology = """\
1 1 0 0 0 10 -1
2 3 1 0 0 2 1
3 3 3 0 0 1 2
"""
        stats = statistics_for_text(morphology)
        self.assertAlmostEqual(stats["median_diameter_by_dendrite"][2], 3.0)
        self.assertAlmostEqual(stats["diameter_taper_by_dendrite"][2]["fraction"], 0.5)
        self.assertAlmostEqual(
            stats["diameter_taper_by_dendrite"][2]["per_length"], 2.0 / 3.0
        )

        zero_length = """\
1 1 0 0 0 10 -1
2 3 0 0 0 2 1
3 3 0 0 0 1 2
"""
        zero_stats = statistics_for_text(zero_length)
        self.assertEqual(zero_stats["diameter_taper_by_dendrite"][2]["per_length"], 0.0)


class BundledMorphologyGoldenTests(unittest.TestCase):
    def test_reference_topology_and_lengths(self):
        parsed = parse_swc_file(BUNDLED_MORPHOLOGY)
        stats = compute_statistics(BUNDLED_MORPHOLOGY)

        self.assertEqual(len(parsed[SAMPLES]), 485)
        self.assertEqual(len(parsed[BRANCH_POINTS]), 17)
        self.assertEqual(len(parsed[DENDRITE_ROOTS]), 39)
        self.assertEqual(len(parsed[BASAL]), 26)
        self.assertEqual(len(parsed[APICAL]), 13)
        self.assertEqual(len(parsed[TERMINALS]), 22)
        self.assertEqual(len(parsed[BASAL_TERMINALS]), 15)
        self.assertEqual(len(parsed[APICAL_TERMINALS]), 7)
        self.assertEqual(
            dict(sorted(Counter(parsed[BRANCH_ORDER].values()).items())),
            {1: 5, 2: 10, 3: 14, 4: 6, 5: 2, 6: 2},
        )
        self.assertEqual(max(parsed[BRANCH_ORDER].values()), 6)
        self.assertAlmostEqual(stats["all_total_length"], 2605.5130433646286)
        self.assertAlmostEqual(stats["all_total_area"], 8718.75174012877)
        self.assertAlmostEqual(stats["all_total_volume"], 3696.0073472414906)
        self.assertAlmostEqual(stats["basal_total_length"], 1575.7592481101744)
        self.assertAlmostEqual(stats["apical_total_length"], 1029.7537952544544)

    def test_second_reference_topology_and_morphometry(self):
        parsed = parse_swc_file(SECOND_BUNDLED_MORPHOLOGY)
        stats = compute_statistics(SECOND_BUNDLED_MORPHOLOGY)

        self.assertEqual(len(parsed[SAMPLES]), 457)
        self.assertEqual(len(parsed[BRANCH_POINTS]), 12)
        self.assertEqual(len(parsed[DENDRITE_ROOTS]), 30)
        self.assertEqual(len(parsed[TERMINALS]), 18)
        self.assertEqual(
            dict(sorted(Counter(parsed[BRANCH_ORDER].values()).items())),
            {1: 6, 2: 10, 3: 8, 4: 4, 5: 2},
        )
        self.assertAlmostEqual(stats["all_total_length"], 2140.5192623696316)
        self.assertAlmostEqual(stats["all_total_area"], 7353.333392267095)
        self.assertAlmostEqual(stats["all_total_volume"], 3283.8597001250155)

    def test_sholl_length_and_regional_partitions_conserve_geometry(self):
        stats = compute_statistics(BUNDLED_MORPHOLOGY, sholl_step=20.0)
        self.assertAlmostEqual(
            sum(stats["sholl_all_length"].values()), stats["all_total_length"]
        )
        self.assertAlmostEqual(
            sum(stats["sholl_basal_length"].values()), stats["basal_total_length"]
        )
        self.assertAlmostEqual(
            sum(stats["sholl_apical_length"].values()), stats["apical_total_length"]
        )

        for measure in ("length", "branchpoints", "intersections"):
            all_values = stats[f"sholl_all_{measure}"]
            basal_values = stats[f"sholl_basal_{measure}"]
            apical_values = stats[f"sholl_apical_{measure}"]
            for bound in set(all_values) | set(basal_values) | set(apical_values):
                self.assertAlmostEqual(
                    all_values.get(bound, 0),
                    basal_values.get(bound, 0) + apical_values.get(bound, 0),
                )


class ShollGeometryTests(unittest.TestCase):
    def setUp(self):
        self.parsed = parse_text(CHORD_MORPHOLOGY)

    def test_line_sphere_intersections_count_outward_and_inward_crossings(self):
        intersections = sholl_intersections(
            self.parsed[SAMPLES],
            self.parsed[PARENTS],
            self.parsed[SOMA_SAMPLES],
            5.0,
            {3},
        )
        self.assertEqual(intersections, {5: 3, 10: 3, 15: 2})

    def test_shell_lengths_are_exact_and_conserve_total_length(self):
        lengths = sholl_length(
            self.parsed[SAMPLES],
            self.parsed[PARENTS],
            self.parsed[SOMA_SAMPLES],
            5.0,
            {3},
        )
        self.assertEqual(set(lengths), {5, 10, 15})
        for value in lengths.values():
            self.assertAlmostEqual(value, 15.0)
        self.assertAlmostEqual(sum(lengths.values()), 45.0)

    def test_fractional_shell_step_retains_exact_boundaries_and_length(self):
        lengths = sholl_length(
            self.parsed[SAMPLES],
            self.parsed[PARENTS],
            self.parsed[SOMA_SAMPLES],
            2.5,
            {3},
        )
        expected_bounds = {2.5, 5.0, 7.5, 10.0, 12.5, 15.0}
        self.assertEqual(set(lengths), expected_bounds)
        for value in lengths.values():
            self.assertAlmostEqual(value, 7.5)
        self.assertAlmostEqual(sum(lengths.values()), 45.0)

    def test_branch_points_are_assigned_to_one_shell(self):
        parsed = parse_text(Y_MORPHOLOGY)
        values = sholl_branch_points(
            parsed[BRANCH_POINTS],
            parsed[SAMPLES],
            parsed[SOMA_SAMPLES],
            1.0,
        )
        self.assertEqual(values, {1: 0, 2: 1})
        self.assertEqual(sum(values.values()), 1)

    def test_near_tangent_secant_is_not_collapsed_to_one_contact(self):
        for label, height, expected in (
            ("near tangent", 0.9999999, 3),
            ("exact tangent", 1.0, 2),
        ):
            morphology = f"""\
1 1 0 0 0 0.5 -1
2 3 -0.001 {height} 0 0.5 1
3 3 0.001 {height} 0 0.5 2
"""
            parsed = parse_text(morphology)
            values = sholl_intersections(
                parsed[SAMPLES],
                parsed[PARENTS],
                parsed[SOMA_SAMPLES],
                1.0,
                {3},
            )
            with self.subTest(label=label):
                self.assertEqual(values[1], expected)

    def test_impractically_small_step_is_rejected_before_allocation(self):
        with self.assertRaisesRegex(ValueError, "more than 10000 radial bins"):
            sholl_length(
                self.parsed[SAMPLES],
                self.parsed[PARENTS],
                self.parsed[SOMA_SAMPLES],
                1e-6,
                {3},
            )


class SerializationTests(unittest.TestCase):
    def test_statistics_are_standard_json_serializable(self):
        stats = compute_statistics(BUNDLED_MORPHOLOGY)
        restored = json.loads(json.dumps(stats))
        self.assertEqual(restored["number_of_all_dendrites"], 39)
        self.assertAlmostEqual(restored["all_total_length"], 2605.5130433646286)

    def test_json_cli_emits_one_parseable_document(self):
        output = StringIO()
        with redirect_stdout(output):
            result = json_main(
                [str(BUNDLED_MORPHOLOGY.parent), BUNDLED_MORPHOLOGY.name]
            )
        self.assertEqual(result, 0)
        self.assertIn(BUNDLED_MORPHOLOGY.name, json.loads(output.getvalue()))

    def test_json_writer_normalizes_numpy_keys_and_scalars(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "statistics.json"
            write_json(path, {np.int64(20): np.float64(1.5)})
            self.assertEqual(json.loads(path.read_text(encoding="utf-8")), {"20": 1.5})


class CommandLineIntegrationTests(unittest.TestCase):
    def run_cli(self, *arguments: str, expected_status: int = 0):
        completed = subprocess.run(
            [sys.executable, str(REPOSITORY / "remod_cli.py"), *arguments],
            cwd=REPOSITORY,
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(
            completed.returncode,
            expected_status,
            msg=f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}",
        )
        return completed

    def test_analysis_writes_deterministic_single_and_aggregate_json(self):
        with tempfile.TemporaryDirectory() as directory_name:
            directory = Path(directory_name)
            (directory / "a.swc").write_text(Y_MORPHOLOGY, encoding="utf-8")
            (directory / "b.swc").write_text(Y_MORPHOLOGY, encoding="utf-8")
            self.run_cli(
                "analyze",
                str(directory),
                "b.swc,a.swc",
                "--sholl-step",
                "2.5",
            )

            statistics = directory / "downloads" / "statistics"
            results = json.loads((statistics / "results.json").read_text())
            summary = json.loads((statistics / "summary.json").read_text())
            self.assertEqual(list(results), ["a.swc", "b.swc"])
            self.assertEqual(summary["file_count"], 2)
            self.assertEqual(summary["files"], ["a.swc", "b.swc"])
            length = summary["scalar_metrics"]["all_total_length"]
            self.assertAlmostEqual(length["mean"], 4.0 + 2.0 * sqrt(2.0))
            self.assertEqual(length["standard_deviation"], 0.0)

    def test_seeded_edit_is_reproducible_valid_and_reanalyzable(self):
        with tempfile.TemporaryDirectory() as directory_name:
            directory = Path(directory_name)
            source = directory / "fixture.swc"
            source.write_text(Y_MORPHOLOGY, encoding="utf-8")
            arguments = (
                "edit",
                "--directory",
                str(directory),
                "--file-name",
                source.name,
                "--who",
                "random_all",
                "--random-ratio",
                "100",
                "--action",
                "branch",
                "--amount",
                "50",
                "--seed",
                "73",
            )
            self.run_cli(*arguments)
            output = directory / "downloads" / "files" / "fixture_new.swc"
            first = output.read_bytes()
            self.run_cli(*arguments)
            self.assertEqual(output.read_bytes(), first)

            parsed = parse_swc_file(output)
            self.assertEqual(len(parsed[BRANCH_POINTS]), 4)
            self.assertEqual(len(parsed[TERMINALS]), 6)
            identifiers = list(parsed[SAMPLES])
            self.assertEqual(identifiers, list(range(1, len(identifiers) + 1)))
            for sample_id, sample in parsed[SAMPLES].items():
                parent = int(sample[6])
                self.assertTrue(parent == -1 or parent < sample_id)
            self.assertNotIn(directory_name, output.read_text(encoding="utf-8"))

            self.run_cli(
                "analyze", str(output.parent), output.name, "--sholl-step", "1"
            )

    def test_invalid_cli_request_fails_without_writing_output(self):
        with tempfile.TemporaryDirectory() as directory_name:
            directory = Path(directory_name)
            source = directory / "fixture.swc"
            source.write_text(Y_MORPHOLOGY, encoding="utf-8")
            self.run_cli(
                "edit",
                "--directory",
                str(directory),
                "--file-name",
                source.name,
                "--who",
                "all_terminal",
                "--action",
                "shrink",
                "--amount",
                "100",
                expected_status=2,
            )
            self.assertFalse((directory / "downloads").exists())

    @unittest.skipUnless(
        importlib.util.find_spec("matplotlib"), "Matplotlib is not installed"
    )
    def test_unbranched_analysis_to_svg_visualization_workflow(self):
        with tempfile.TemporaryDirectory() as directory_name:
            directory = Path(directory_name)
            (directory / "fixture.swc").write_text(
                UNBRANCHED_MORPHOLOGY, encoding="utf-8"
            )
            self.run_cli("analyze", str(directory), "fixture.swc", "--sholl-step", "1")

            results = json.loads(
                (directory / "downloads" / "statistics" / "results.json").read_text()
            )["fixture.swc"]
            self.assertEqual(
                results["sholl_all_branchpoints"],
                {str(bound): 0 for bound in range(1, 6)},
            )

            self.run_cli(
                "edit",
                "--directory",
                str(directory),
                "--file-name",
                "fixture.swc",
                "--who",
                "all_dendrites",
                "--action",
                "remove",
            )
            soma_only = directory / "downloads" / "files" / "fixture_new.swc"
            self.run_cli("analyze", str(soma_only.parent), soma_only.name)

            command = [
                sys.executable,
                str(REPOSITORY / "plot_statistics.py"),
                str(soma_only.parent),
            ]
            completed = subprocess.run(
                command,
                cwd=REPOSITORY,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(completed.returncode, 0, msg=completed.stderr)
            plot_directory = (
                soma_only.parent / "downloads" / "statistics" / "plots" / "aggregate"
            )
            first = {
                path.name: path.read_bytes() for path in plot_directory.glob("*.svg")
            }
            self.assertEqual(len(first), 10)

            repeated = subprocess.run(
                command,
                cwd=REPOSITORY,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(repeated.returncode, 0, msg=repeated.stderr)
            second = {
                path.name: path.read_bytes() for path in plot_directory.glob("*.svg")
            }
            self.assertEqual(second, first)


class SeededSelectionTests(unittest.TestCase):
    def test_empirical_growth_distribution_is_normalized_and_seedable(self):
        lengths, weights = parse_length_distribution()
        self.assertEqual(len(lengths), 533)
        self.assertEqual(len(weights), len(lengths))
        self.assertAlmostEqual(sum(weights), 1.0)
        first = select_length(lengths, weights, random.Random(91))
        second = select_length(lengths, weights, random.Random(91))
        self.assertEqual(first, second)
        self.assertIn(first, lengths)

    def test_seeded_selection_is_reproducible_uniform_and_without_replacement(self):
        options = list(range(1, 11))
        samples = {root: [[root]] for root in options}
        first, label = sample_random_dendrites(
            options, "all", samples, 0.3, random.Random(123)
        )
        second, _ = sample_random_dendrites(
            options, "all", samples, 0.3, random.Random(123)
        )
        self.assertEqual(first, [1, 2, 5])
        self.assertEqual(second, first)
        self.assertEqual(len(first), len(set(first)))
        self.assertIn("30%", label)

    def test_ratio_rounding_and_validation_are_explicit(self):
        options = [1, 2, 3, 4, 5]
        samples = {root: [[root]] for root in options}
        selected, _ = sample_random_dendrites(
            options, "all", samples, 0.5, random.Random(5)
        )
        self.assertEqual(len(selected), 3)
        self.assertEqual(sample_random_dendrites(options, "all", samples, 0)[0], [])
        self.assertEqual(
            sample_random_dendrites(options, "all", samples, 1, random.Random(1))[0],
            options,
        )
        for invalid in (-0.01, 1.01):
            with self.subTest(ratio=invalid), self.assertRaises(ValueError):
                sample_random_dendrites(options, "all", samples, invalid)


class RemodelingInvariantTests(unittest.TestCase):
    def test_terminal_shrink_is_exact_and_does_not_move_other_samples(self):
        before, after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY, [4], "shrink", 50.0
        )
        self.assertAlmostEqual(after[LENGTHS][4], before[LENGTHS][4] * 0.5)
        self.assertAlmostEqual(
            total_dendritic_length(after),
            total_dendritic_length(before) - before[LENGTHS][4] * 0.5,
        )
        for sample_id in (1, 2, 3, 5, 6, 7):
            self.assertEqual(after[SAMPLES][sample_id], before[SAMPLES][sample_id])

    def test_shrink_retains_the_crossed_cylindrical_edge_radius(self):
        morphology = """\
1 1 0 0 0 10 -1
2 3 2 0 0 1 1
"""
        _before, after, _lines, _roots, _samples = remodel(
            morphology, [2], "shrink", 50.0
        )
        self.assertAlmostEqual(after[SAMPLES][2][5], 1.0)
        self.assertAlmostEqual(after[LENGTHS][2], 1.0)
        self.assertAlmostEqual(sum(after[AREAS].values()), 2.0 * pi)
        self.assertAlmostEqual(total_dendritic_volume(after), pi)

    def test_nonterminal_shrink_translates_descendants_rigidly(self):
        before, after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY, [2], "shrink", 25.0
        )
        self.assertAlmostEqual(after[LENGTHS][2], 1.5)
        self.assertAlmostEqual(after[LENGTHS][4], before[LENGTHS][4])
        self.assertAlmostEqual(after[LENGTHS][5], before[LENGTHS][5])
        for child in (4, 5):
            before_vector = np.asarray(before[SAMPLES][child][2:5]) - np.asarray(
                before[SAMPLES][3][2:5]
            )
            after_vector = np.asarray(after[SAMPLES][child][2:5]) - np.asarray(
                after[SAMPLES][3][2:5]
            )
            np.testing.assert_allclose(after_vector, before_vector)

    def test_remove_deletes_the_complete_subtree_without_orphans(self):
        _before, after, _lines, _roots, _samples = remodel(Y_MORPHOLOGY, [2], "remove")
        self.assertEqual(set(after[SAMPLES]), {1, 6, 7})
        self.assertEqual(after[DENDRITE_ROOTS], [6])
        self.assertEqual(after[TERMINALS], [6])
        for sample in after[SAMPLES].values():
            self.assertTrue(int(sample[6]) == -1 or int(sample[6]) in after[SAMPLES])

    def test_nonterminal_extend_adds_exact_length_and_preserves_distal_geometry(self):
        before, after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY, [2], "extend", 1.0, "micrometers", seed=31
        )
        self.assertAlmostEqual(
            total_dendritic_length(after), total_dendritic_length(before) + 1.0
        )
        self.assertAlmostEqual(after[LENGTHS][2], before[LENGTHS][2] + 1.0)
        self.assertAlmostEqual(after[LENGTHS][4], before[LENGTHS][4])
        self.assertAlmostEqual(after[LENGTHS][5], before[LENGTHS][5])
        new_ids = set(after[SAMPLES]) - set(before[SAMPLES])
        self.assertTrue(new_ids)
        self.assertTrue(new_ids.issubset(after[SAMPLE_IDS_BY_SEGMENT][2]))
        new_tip = int(after[SAMPLES][4][6])
        self.assertIn(new_tip, new_ids)
        self.assertEqual(int(after[SAMPLES][4][6]), new_tip)
        self.assertEqual(int(after[SAMPLES][5][6]), new_tip)

    def test_branch_adds_two_daughters_of_the_requested_length(self):
        before, after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY, [4], "branch", 50.0, seed=41
        )
        target_length = before[LENGTHS][4] * 0.5
        daughters = sorted(
            sample_id
            for sample_id, sample in after[SAMPLES].items()
            if int(sample[6]) == 4
        )
        self.assertEqual(len(daughters), 2)
        self.assertEqual(len(after[BRANCH_POINTS]), len(before[BRANCH_POINTS]) + 1)
        self.assertEqual(len(after[DENDRITE_ROOTS]), len(before[DENDRITE_ROOTS]) + 2)
        self.assertEqual(len(after[TERMINALS]), len(before[TERMINALS]) + 1)
        for daughter in daughters:
            self.assertAlmostEqual(after[LENGTHS][daughter], target_length)
        self.assertAlmostEqual(
            total_dendritic_length(after),
            total_dendritic_length(before) + 2.0 * target_length,
        )

    def test_tiny_representable_extension_is_not_silently_ignored(self):
        before, after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY, [4], "extend", 1e-11, "micrometers", seed=43
        )
        added = total_dendritic_length(after) - total_dendritic_length(before)
        self.assertAlmostEqual(added, 1e-11, delta=1e-13)

    def test_scale_changes_all_selected_linear_dimensions_by_one_factor(self):
        before = parse_text(Y_MORPHOLOGY)
        before_roots = list(before[DENDRITE_ROOTS])
        _before, after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY, before_roots, "scale", 200.0
        )
        self.assertAlmostEqual(
            total_dendritic_length(after), 2.0 * total_dendritic_length(before)
        )
        self.assertAlmostEqual(
            sum(after[AREAS].values()), 4.0 * sum(before[AREAS].values())
        )
        self.assertAlmostEqual(
            total_dendritic_volume(after), 8.0 * total_dendritic_volume(before)
        )
        for root in before_roots:
            self.assertAlmostEqual(after[LENGTHS][root], 2.0 * before[LENGTHS][root])
        for sample_id, sample in before[SAMPLES].items():
            if int(sample[1]) in {3, 4}:
                np.testing.assert_allclose(
                    after[SAMPLES][sample_id][2:5],
                    2.0 * np.asarray(sample[2:5], dtype=float),
                )
                self.assertAlmostEqual(after[SAMPLES][sample_id][5], 2.0 * sample[5])
        self.assertEqual(after[SAMPLES][1], before[SAMPLES][1])

    def test_scale_can_target_one_region_without_changing_the_other(self):
        before = parse_text(Y_MORPHOLOGY)
        _before, after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY, before[BASAL], "scale", 150.0
        )
        for root in before[BASAL]:
            self.assertAlmostEqual(after[LENGTHS][root], 1.5 * before[LENGTHS][root])
        for root in before[APICAL]:
            self.assertAlmostEqual(after[LENGTHS][root], before[LENGTHS][root])
            for sample_id in before[SAMPLE_IDS_BY_SEGMENT][root]:
                self.assertEqual(after[SAMPLES][sample_id], before[SAMPLES][sample_id])

    def test_radius_change_supports_percent_and_absolute_units(self):
        before, percent_after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY,
            [4],
            "none",
            radius_change=50.0,
            radius_unit="percent",
        )
        self.assertAlmostEqual(percent_after[SAMPLES][4][5], 0.75)
        self.assertEqual(percent_after[SAMPLES][5], before[SAMPLES][5])

        _before, absolute_after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY,
            [4],
            "none",
            radius_change=-0.1,
            radius_unit="micrometers",
        )
        self.assertAlmostEqual(absolute_after[SAMPLES][4][5], 0.4)

    def test_invalid_actions_fail_instead_of_emitting_invalid_geometry(self):
        with self.assertRaisesRegex(ValueError, "entire segment"):
            remodel(Y_MORPHOLOGY, [4], "shrink", 100.0)
        with self.assertRaisesRegex(ValueError, "non-positive radius"):
            remodel(
                Y_MORPHOLOGY,
                [4],
                "none",
                radius_change=-0.5,
                radius_unit="micrometers",
            )
        with self.assertRaisesRegex(ValueError, "more than 100000 samples"):
            remodel(
                Y_MORPHOLOGY,
                [4],
                "extend",
                1e20,
                "micrometers",
            )
        overflowing = """\
1 1 0 0 0 1 -1
2 3 1e200 0 0 0.5 1
"""
        with self.assertRaisesRegex(ValueError, "scale exceeds finite numeric range"):
            remodel(overflowing, [2], "scale", 1e200)


if __name__ == "__main__":
    unittest.main()
