"""Regression tests for the morphology contract implemented by REMOD.

The synthetic fixtures have analytically tractable topology and geometry.  The
bundled morphology assertions are independent reference values, rather than
snapshots generated by the implementation under test.
"""

from __future__ import annotations

from collections import Counter
import importlib.util
import json
from math import pi, sqrt
from pathlib import Path
import random
import subprocess
import sys
import tempfile
import unittest

import numpy as np

from core_utils import sample_random_dendrites
from file_io import write_json
from json_stats import compute_statistics, summarize_statistics
from morphology_statistics import (
    sholl_branch_points,
    sholl_intersections,
    sholl_length,
    sholl_profiles,
)
from remod_engine import (
    AnalysisCache,
    RemodelRequest,
    analyze_text,
    remodel_text,
    validate_remodel_request,
)
from remod_ui import _optional_number
from remodeling_actions import execute_action, parse_length_distribution, select_length
from swc_parser import (
    dendrite_volumes,
    parse_swc_file,
    parse_swc_lines,
    parse_swc_text,
    validate_samples,
)


REPOSITORY = Path(__file__).resolve().parent
BUNDLED_MORPHOLOGY = REPOSITORY / "swc_files" / "0-2.CNG.swc"
SECOND_BUNDLED_MORPHOLOGY = REPOSITORY / "swc_files" / "0-2a.CNG.swc"

Y_MORPHOLOGY = """\
# Analytic two-region morphology
1 1 0 0 0 0.5 -1
2 3 1 0 0 0.5 1
3 3 2 0 0 0.5 2
4 3 3 1 0 0.5 3
5 3 3 -1 0 0.5 3
6 4 0 1 0 0.5 1
7 4 0 2 0 0.5 6
"""


CHORD_MORPHOLOGY = """\
1 1 0 0 0 0.5 -1
2 3 15 0 0 0.5 1
3 3 -15 0 0 0.5 2
"""


UNBRANCHED_MORPHOLOGY = """\
1 1 0 0 0 0.5 -1
2 3 5 0 0 0.5 1
"""


def parse_text(text: str):
    """Parse an in-memory fixture through the public file parser."""

    with tempfile.TemporaryDirectory() as directory:
        path = Path(directory) / "fixture.swc"
        path.write_text(text, encoding="utf-8")
        return parse_swc_file(path)


def statistics_for_text(text: str):
    """Compute statistics for an in-memory fixture."""

    with tempfile.TemporaryDirectory() as directory:
        path = Path(directory) / "fixture.swc"
        path.write_text(text, encoding="utf-8")
        return compute_statistics(path)


def total_dendritic_length(parsed) -> float:
    return sum(parsed.lengths[root] for root in parsed.dendrite_roots)


def total_dendritic_volume(parsed) -> float:
    volumes = dendrite_volumes(
        parsed.segments,
        parsed.dendrite_roots,
        parsed.parents,
        parsed.samples,
    )
    return sum(volumes.values())


def segment_sample_ids(parsed) -> dict[int, list[int]]:
    return {
        root: [int(sample[0]) for sample in segment]
        for root, segment in parsed.segments.items()
    }


def remodel(
    morphology: str,
    targets,
    action: str,
    amount=None,
    extent_unit: str = "percent",
    radius_change=None,
    radius_unit: str = "percent",
    seed: int = 17,
):
    """Run an action on a fresh fixture and reparse its serialized result."""

    before = parse_text(morphology)
    working = parse_text(morphology)
    lines = execute_action(
        targets,
        action,
        amount,
        extent_unit,
        working.segments,
        working.lengths,
        radius_change,
        working.anchor_samples,
        working.descendants,
        radius_unit=radius_unit,
        seed=seed,
        growth_origin=working.root_sample[2:5] if working.root_is_soma else None,
        plane_axis=(
            {"x": 0, "y": 1, "z": 2}[working.constant_axes[0]]
            if working.spatial_dimension == 2 and len(working.constant_axes) == 1
            else None
        ),
    )
    _comments, serialized_samples = parse_swc_lines(lines)
    validate_samples(serialized_samples)
    after = parse_text("\n".join(lines) + "\n")
    return before, after, lines, after.dendrite_roots, []


class StrictSWCParsingTests(unittest.TestCase):
    def test_comments_blanks_and_valid_rows_are_parsed(self):
        comments, samples = parse_swc_lines(
            ["# source", "", "1 1 0 0 0 1 -1", "2 3 1 0 0 0.5 1"]
        )
        validate_samples(samples)
        self.assertEqual(comments, ["# source"])
        self.assertEqual(set(samples), {1, 2})

    def test_malformed_rows_and_values_are_rejected(self):
        cases = {
            "too few columns": ["1 1 0 0 0 1"],
            "too many columns": ["1 1 0 0 0 1 -1 extra"],
            "non-integer identifier": ["one 1 0 0 0 1 -1"],
            "non-positive identifier": ["0 1 0 0 0 1 -1"],
            "non-finite coordinate": ["1 1 nan 0 0 1 -1"],
            "zero radius": ["1 1 0 0 0 0 -1"],
            "negative radius": ["1 1 0 0 0 -0.1 -1"],
            "duplicate identifier": [
                "1 1 0 0 0 1 -1",
                "1 3 1 0 0 0.5 1",
            ],
        }
        for label, lines in cases.items():
            with self.subTest(label=label), self.assertRaises(ValueError):
                parse_swc_lines(lines)

    def test_invalid_topologies_are_rejected(self):
        cases = {
            "missing parent": [
                "1 1 0 0 0 1 -1",
                "2 3 1 0 0 0.5 99",
            ],
            "self parent": [
                "1 1 0 0 0 1 -1",
                "2 3 1 0 0 0.5 2",
            ],
            "no root": [
                "1 1 0 0 0 1 2",
                "2 3 1 0 0 0.5 1",
            ],
            "non-soma root": [
                "1 1 0 0 0 1 -1",
                "2 3 1 0 0 0.5 -1",
            ],
            "multiple soma roots": [
                "1 1 0 0 0 1 -1",
                "2 1 1 0 0 1 -1",
            ],
            "soma below neurite": [
                "1 1 0 0 0 1 -1",
                "2 3 1 0 0 0.5 1",
                "3 1 2 0 0 1 2",
            ],
            "cycle": [
                "1 1 0 0 0 1 -1",
                "2 3 1 0 0 0.5 3",
                "3 3 2 0 0 0.5 2",
            ],
        }
        for label, lines in cases.items():
            with self.subTest(label=label):
                _comments, samples = parse_swc_lines(lines)
                with self.assertRaises(ValueError):
                    validate_samples(samples)


class TolerantMorphologyDiagnosticsTests(unittest.TestCase):
    def test_non_soma_root_retains_root_independent_analysis_and_editing(self):
        morphology = """\
1 3 0 0 0 0.5 -1
2 3 1 0 0 0.5 1
3 3 2 0 0 0.5 2
4 3 3 1 0 0.5 3
5 3 3 -1 0 0.5 3
"""
        analysis = analyze_text(morphology, 1.0)
        geometry = analysis["morphology"]
        statistics = analysis["statistics"]

        self.assertFalse(geometry["root"]["is_soma"])
        self.assertEqual(geometry["counts"]["segments"], 3)
        self.assertEqual(geometry["counts"]["dendrites"], 3)
        self.assertAlmostEqual(statistics["all_arbor_total_length"], 2.0 + 2.0 * sqrt(2.0))
        self.assertEqual(statistics["sholl_all_length"], {})
        self.assertAlmostEqual(
            sum(statistics["radial_all_arbor_length"].values()),
            statistics["all_arbor_total_length"],
        )
        self.assertFalse(
            statistics["capabilities"]["soma_centered_sholl"]["supported"]
        )
        self.assertIn(
            "NO_SOMA_ROOT", {item["code"] for item in statistics["warnings"]}
        )

        edited = remodel_text(
            morphology,
            RemodelRequest(
                "rootless.swc",
                "manual",
                "shrink",
                manual_segments="4",
                amount=25.0,
            ),
        )
        self.assertFalse(edited.parsed.root_is_soma)
        self.assertLess(edited.parsed.lengths[4], 2.0 ** 0.5)

    def test_types_six_and_seven_are_explicit_generic_arbors(self):
        for sample_type, count_key, warning_code in (
            (6, "number_of_unspecified_neurite_segments", "UNSPECIFIED_NEURITES_TYPE_6"),
            (7, "number_of_glial_process_segments", "GLIAL_PROCESSES_TYPE_7"),
        ):
            morphology = f"""\
1 1 0 0 0 1 -1
2 {sample_type} 1 0 0 0.5 1
3 {sample_type} 2 0 0 0.5 2
4 {sample_type} 3 1 0 0.5 3
5 {sample_type} 3 -1 0 0.5 3
"""
            with self.subTest(sample_type=sample_type):
                analysis = analyze_text(morphology, 1.0)
                stats = analysis["statistics"]
                self.assertEqual(stats["number_of_all_dendrites"], 0)
                self.assertEqual(stats["number_of_all_arbor_segments"], 3)
                self.assertEqual(stats[count_key], 3)
                self.assertGreater(stats["all_arbor_total_length"], 0.0)
                self.assertIn(
                    warning_code, {item["code"] for item in stats["warnings"]}
                )

                selector = (
                    "all_unspecified_neurites"
                    if sample_type == 6
                    else "all_glial_processes"
                )
                scaled = remodel_text(
                    morphology,
                    RemodelRequest(
                        "arbor.swc", selector, "scale", amount=125.0
                    ),
                )
                self.assertGreater(
                    sum(scaled.parsed.lengths.values()),
                    stats["all_arbor_total_length"],
                )
                with self.assertRaisesRegex(ValueError, "dendrite-derived growth model"):
                    remodel_text(
                        morphology,
                        RemodelRequest(
                            "arbor.swc", selector, "branch", amount=25.0
                        ),
                    )

    def test_suspicious_internal_jump_warns_but_remains_analyzable(self):
        morphology = """\
1 1 0 0 0 1 -1
2 3 1 0 0 0.5 1
3 3 2 0 0 0.5 2
4 3 3 0 0 0.5 3
5 3 4 0 0 0.5 4
6 3 5 0 0 0.5 5
7 3 30 0 0 0.5 6
8 3 31 0 0 0.5 7
"""
        analysis = analyze_text(morphology, 2.0)
        stats = analysis["statistics"]
        gap = next(
            item
            for item in stats["warnings"]
            if item["code"] == "GEOMETRIC_DENDRITE_GAP"
        )
        self.assertIn(7, gap["sample_ids"])
        self.assertAlmostEqual(stats["all_total_length"], 31.0)
        self.assertAlmostEqual(stats["all_arbor_total_length"], 31.0)

    def test_comments_are_provenance_only_and_planar_growth_stays_planar(self):
        morphology = """\
# maintainer: legacy@example.org
# source: /Users/legacy/private/reconstruction.asc
1 1 0 0 2 1 -1
2 3 1 0 2 0.5 1
3 3 2 0 2 0.5 2
"""
        parsed = parse_swc_text(morphology)
        self.assertEqual(len(parsed.comments), 2)
        self.assertEqual(parsed.spatial_dimension, 1)
        self.assertIn(
            "COORDINATE_UNIT_UNSPECIFIED",
            {item["code"] for item in parsed.warnings},
        )

        planar = remodel_text(
            Y_MORPHOLOGY,
            RemodelRequest(
                "planar.swc",
                "manual",
                "branch",
                manual_segments="4",
                amount=50.0,
                seed=9,
            ),
        )
        self.assertEqual({float(sample[4]) for sample in planar.parsed.samples.values()}, {0.0})


class SegmentTopologyAndGeometryTests(unittest.TestCase):
    def setUp(self):
        self.parsed = parse_text(Y_MORPHOLOGY)

    def test_segments_begin_after_soma_or_bifurcation(self):
        parsed = self.parsed
        self.assertEqual(parsed.dendrite_roots, [2, 4, 5, 6])
        self.assertEqual(
            segment_sample_ids(parsed),
            {2: [2, 3], 4: [4], 5: [5], 6: [6, 7]},
        )
        self.assertEqual(parsed.branch_points, [3])
        self.assertEqual(parsed.root_paths, {2: [2], 4: [4, 2], 5: [5, 2], 6: [6]})
        self.assertEqual(parsed.descendants, {2: [4, 5], 4: [], 5: [], 6: []})
        self.assertEqual(parsed.all_terminal, [4, 5, 6])
        self.assertEqual(parsed.basal_terminal, [4, 5])
        self.assertEqual(parsed.apical_terminal, [6])
        self.assertEqual(parsed.branch_order, {2: 1, 4: 2, 5: 2, 6: 1})

    def test_lengths_areas_and_volumes_match_closed_form_values(self):
        parsed = self.parsed
        expected_total_length = 4.0 + 2.0 * sqrt(2.0)
        self.assertAlmostEqual(total_dendritic_length(parsed), expected_total_length)
        self.assertAlmostEqual(
            sum(parsed.surface_areas.values()), pi * expected_total_length
        )
        self.assertAlmostEqual(
            total_dendritic_volume(parsed), pi * expected_total_length / 4.0
        )

    def test_numeric_overflow_is_rejected(self):
        morphology = """\
1 1 -1e308 0 0 1 -1
2 3 1e308 0 0 0.5 1
"""
        with self.assertRaisesRegex(ValueError, "finite numeric range"):
            parse_text(morphology)

    def test_area_and_volume_use_the_distal_sample_radius(self):
        morphology = """\
1 1 0 0 0 10 -1
2 3 2 0 0 1 1
3 3 5 0 0 2 2
"""
        parsed = parse_text(morphology)
        self.assertAlmostEqual(sum(parsed.surface_areas.values()), 16.0 * pi)
        self.assertAlmostEqual(total_dendritic_volume(parsed), 14.0 * pi)

    def test_type_change_starts_a_segment_without_incrementing_branch_order(self):
        morphology = """\
1 1 0 0 0 1 -1
2 3 1 0 0 0.5 1
3 4 2 0 0 0.5 2
4 4 3 0 0 0.5 3
"""
        parsed = parse_text(morphology)
        self.assertEqual(parsed.dendrite_roots, [2, 3])
        self.assertEqual(parsed.branch_points, [])
        self.assertEqual(parsed.branch_order, {2: 1, 3: 1})

    def test_diameter_and_taper_conventions_have_analytic_values(self):
        morphology = """\
1 1 0 0 0 10 -1
2 3 1 0 0 2 1
3 3 3 0 0 1 2
"""
        stats = statistics_for_text(morphology)
        self.assertAlmostEqual(stats["median_diameter_by_dendrite"][2], 3.0)
        self.assertAlmostEqual(stats["diameter_taper_by_dendrite"][2]["fraction"], 0.5)
        self.assertAlmostEqual(
            stats["diameter_taper_by_dendrite"][2]["per_length"], 2.0 / 3.0
        )

        zero_length = """\
1 1 0 0 0 10 -1
2 3 0 0 0 2 1
3 3 0 0 0 1 2
"""
        zero_stats = statistics_for_text(zero_length)
        self.assertEqual(zero_stats["diameter_taper_by_dendrite"][2]["per_length"], 0.0)


class BundledMorphologyGoldenTests(unittest.TestCase):
    def test_reference_topology_and_lengths(self):
        parsed = parse_swc_file(BUNDLED_MORPHOLOGY)
        stats = compute_statistics(BUNDLED_MORPHOLOGY)

        self.assertEqual(len(parsed.samples), 485)
        self.assertEqual(len(parsed.branch_points), 17)
        self.assertEqual(len(parsed.dendrite_roots), 39)
        self.assertEqual(len(parsed.basal), 26)
        self.assertEqual(len(parsed.apical), 13)
        self.assertEqual(len(parsed.all_terminal), 22)
        self.assertEqual(len(parsed.basal_terminal), 15)
        self.assertEqual(len(parsed.apical_terminal), 7)
        self.assertEqual(
            dict(sorted(Counter(parsed.branch_order.values()).items())),
            {1: 5, 2: 10, 3: 14, 4: 6, 5: 2, 6: 2},
        )
        self.assertEqual(max(parsed.branch_order.values()), 6)
        self.assertAlmostEqual(stats["all_total_length"], 2605.5130433646286)
        self.assertAlmostEqual(stats["all_total_area"], 8718.75174012877)
        self.assertAlmostEqual(stats["all_total_volume"], 3696.0073472414906)
        self.assertAlmostEqual(stats["basal_total_length"], 1575.7592481101744)
        self.assertAlmostEqual(stats["apical_total_length"], 1029.7537952544544)

    def test_second_reference_topology_and_morphometry(self):
        parsed = parse_swc_file(SECOND_BUNDLED_MORPHOLOGY)
        stats = compute_statistics(SECOND_BUNDLED_MORPHOLOGY)

        self.assertEqual(len(parsed.samples), 457)
        self.assertEqual(len(parsed.branch_points), 12)
        self.assertEqual(len(parsed.dendrite_roots), 30)
        self.assertEqual(len(parsed.all_terminal), 18)
        self.assertEqual(
            dict(sorted(Counter(parsed.branch_order.values()).items())),
            {1: 6, 2: 10, 3: 8, 4: 4, 5: 2},
        )
        self.assertAlmostEqual(stats["all_total_length"], 2140.5192623696316)
        self.assertAlmostEqual(stats["all_total_area"], 7353.333392267095)
        self.assertAlmostEqual(stats["all_total_volume"], 3283.8597001250155)

    def test_sholl_length_and_regional_partitions_conserve_geometry(self):
        stats = compute_statistics(BUNDLED_MORPHOLOGY, sholl_step=20.0)
        self.assertAlmostEqual(
            sum(stats["sholl_all_length"].values()), stats["all_total_length"]
        )
        self.assertAlmostEqual(
            sum(stats["sholl_basal_length"].values()), stats["basal_total_length"]
        )
        self.assertAlmostEqual(
            sum(stats["sholl_apical_length"].values()), stats["apical_total_length"]
        )

        for measure in ("length", "branchpoints", "intersections"):
            all_values = stats[f"sholl_all_{measure}"]
            basal_values = stats[f"sholl_basal_{measure}"]
            apical_values = stats[f"sholl_apical_{measure}"]
            for bound in set(all_values) | set(basal_values) | set(apical_values):
                self.assertAlmostEqual(
                    all_values.get(bound, 0),
                    basal_values.get(bound, 0) + apical_values.get(bound, 0),
                )


class ShollGeometryTests(unittest.TestCase):
    def setUp(self):
        self.parsed = parse_text(CHORD_MORPHOLOGY)

    def test_line_sphere_intersections_count_outward_and_inward_crossings(self):
        intersections = sholl_intersections(
            self.parsed.samples,
            self.parsed.parents,
            self.parsed.soma_samples,
            5.0,
            {3},
        )
        self.assertEqual(intersections, {5: 3, 10: 3, 15: 2})

    def test_shell_lengths_are_exact_and_conserve_total_length(self):
        lengths = sholl_length(
            self.parsed.samples,
            self.parsed.parents,
            self.parsed.soma_samples,
            5.0,
            {3},
        )
        self.assertEqual(set(lengths), {5, 10, 15})
        for value in lengths.values():
            self.assertAlmostEqual(value, 15.0)
        self.assertAlmostEqual(sum(lengths.values()), 45.0)

    def test_fractional_shell_step_retains_exact_boundaries_and_length(self):
        lengths = sholl_length(
            self.parsed.samples,
            self.parsed.parents,
            self.parsed.soma_samples,
            2.5,
            {3},
        )
        expected_bounds = {2.5, 5.0, 7.5, 10.0, 12.5, 15.0}
        self.assertEqual(set(lengths), expected_bounds)
        for value in lengths.values():
            self.assertAlmostEqual(value, 7.5)
        self.assertAlmostEqual(sum(lengths.values()), 45.0)

    def test_branch_points_are_assigned_to_one_shell(self):
        parsed = parse_text(Y_MORPHOLOGY)
        values = sholl_branch_points(
            parsed.branch_points,
            parsed.samples,
            parsed.soma_samples,
            1.0,
        )
        self.assertEqual(values, {1: 0, 2: 1})
        self.assertEqual(sum(values.values()), 1)

    def test_near_tangent_secant_is_not_collapsed_to_one_contact(self):
        for label, height, expected in (
            ("near tangent", 0.9999999, 3),
            ("exact tangent", 1.0, 2),
        ):
            morphology = f"""\
1 1 0 0 0 0.5 -1
2 3 -0.001 {height} 0 0.5 1
3 3 0.001 {height} 0 0.5 2
"""
            parsed = parse_text(morphology)
            values = sholl_intersections(
                parsed.samples,
                parsed.parents,
                parsed.soma_samples,
                1.0,
                {3},
            )
            with self.subTest(label=label):
                self.assertEqual(values[1], expected)

    def test_impractically_small_step_is_rejected_before_allocation(self):
        with self.assertRaisesRegex(ValueError, "more than 10000 radial bins"):
            sholl_length(
                self.parsed.samples,
                self.parsed.parents,
                self.parsed.soma_samples,
                1e-6,
                {3},
            )


class SerializationTests(unittest.TestCase):
    def test_statistics_are_standard_json_serializable(self):
        stats = compute_statistics(BUNDLED_MORPHOLOGY)
        restored = json.loads(json.dumps(stats))
        self.assertEqual(restored["number_of_all_dendrites"], 39)
        self.assertAlmostEqual(restored["all_total_length"], 2605.5130433646286)

    def test_json_writer_normalizes_numpy_keys_and_scalars(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "statistics.json"
            write_json(path, {np.int64(20): np.float64(1.5)})
            self.assertEqual(json.loads(path.read_text(encoding="utf-8")), {"20": 1.5})

    def test_cohort_distribution_missing_bins_follow_metric_semantics(self):
        summary = summarize_statistics(
            {
                "a.swc": {
                    "sholl_all_length": {20: 5.0, 40: 2.0},
                    "all_dendritic_length_per_branch_order": {1: 10.0, 2: 20.0},
                    "path_length_by_segment": {2: 10.0},
                    "capabilities": {"soma_centered_sholl": {"supported": True}},
                },
                "b.swc": {
                    "sholl_all_length": {20: 7.0},
                    "all_dendritic_length_per_branch_order": {1: 30.0},
                    "path_length_by_segment": {2: 30.0},
                    "capabilities": {"soma_centered_sholl": {"supported": True}},
                },
            }
        )
        sholl_bin = summary["distribution_metrics"]["sholl_all_length"]["40"]
        branch_bin = summary["distribution_metrics"][
            "all_dendritic_length_per_branch_order"
        ]["2"]

        self.assertEqual(sholl_bin, {"mean": 1.0, "standard_deviation": 1.0, "sample_count": 2})
        self.assertEqual(branch_bin, {"mean": 20.0, "standard_deviation": 0.0, "sample_count": 1})
        self.assertNotIn("path_length_by_segment", summary["distribution_metrics"])

    def test_cohort_profiles_exclude_explicitly_unsupported_morphologies(self):
        summary = summarize_statistics(
            {
                "soma.swc": {
                    "sholl_all_length": {20: 8.0},
                    "capabilities": {"soma_centered_sholl": {"supported": True}},
                },
                "rootless.swc": {
                    "sholl_all_length": {},
                    "capabilities": {"soma_centered_sholl": {"supported": False}},
                },
            }
        )
        self.assertEqual(
            summary["distribution_metrics"]["sholl_all_length"]["20"],
            {"mean": 8.0, "standard_deviation": 0.0, "sample_count": 1},
        )

    def test_cohort_dendrite_metrics_exclude_unclassified_arbors(self):
        summary = summarize_statistics(
            {
                "dendrite.swc": {
                    "all_total_length": 12.0,
                    "all_arbor_total_length": 12.0,
                    "capabilities": {
                        "dendrite_specific_morphometrics": {"supported": True}
                    },
                },
                "unspecified.swc": {
                    "all_total_length": 0.0,
                    "all_arbor_total_length": 8.0,
                    "capabilities": {
                        "dendrite_specific_morphometrics": {"supported": False}
                    },
                },
            }
        )
        self.assertEqual(
            summary["scalar_metrics"]["all_total_length"],
            {"mean": 12.0, "standard_deviation": 0.0, "sample_count": 1},
        )
        self.assertEqual(
            summary["scalar_metrics"]["all_arbor_total_length"],
            {"mean": 10.0, "standard_deviation": 2.0, "sample_count": 2},
        )
        self.assertEqual(
            summary["capability_counts"]["dendrite_specific_morphometrics"], 1
        )


class InMemoryEngineTests(unittest.TestCase):
    def test_analysis_reuses_one_parsed_morphology_for_ui_geometry_and_statistics(self):
        analysis = analyze_text(Y_MORPHOLOGY, 1.0)
        parsed = parse_swc_text(Y_MORPHOLOGY)

        self.assertEqual(analysis["morphology"]["counts"]["samples"], 7)
        self.assertEqual(analysis["morphology"]["counts"]["segments"], 4)
        self.assertEqual(
            analysis["statistics"]["all_total_length"],
            sum(parsed.lengths[root] for root in parsed.dendrite_roots),
        )

    def test_text_remodeling_is_reparsed_and_preserves_a_deterministic_header(self):
        result = remodel_text(
            Y_MORPHOLOGY,
            RemodelRequest(
                file_name="fixture.swc",
                who="all_terminal",
                action="shrink",
                amount=10.0,
                seed=41,
            ),
        )

        self.assertEqual(result.targets, (4, 5, 6))
        self.assertIn("# REMOD edited morphology", result.content)
        self.assertIn("# source_file: fixture.swc", result.content)
        self.assertIn("# Analytic two-region morphology", result.content)
        self.assertLess(
            sum(result.parsed.lengths.values()),
            sum(parse_swc_text(Y_MORPHOLOGY).lengths.values()),
        )

    def test_combined_sholl_profiles_match_the_focused_public_helpers(self):
        parsed = parse_swc_file(BUNDLED_MORPHOLOGY)
        profiles = sholl_profiles(
            parsed.samples, parsed.parents, parsed.soma_samples, 20.0
        )
        for name, types in (("all", {3, 4}), ("basal", {3}), ("apical", {4})):
            self.assertEqual(
                profiles[name]["length"],
                sholl_length(
                    parsed.samples,
                    parsed.parents,
                    parsed.soma_samples,
                    20.0,
                    types,
                ),
            )
            self.assertEqual(
                profiles[name]["intersections"],
                sholl_intersections(
                    parsed.samples,
                    parsed.parents,
                    parsed.soma_samples,
                    20.0,
                    types,
                ),
            )

    def test_compact_geometry_contract_is_columnar_and_complete(self):
        analysis = analyze_text(Y_MORPHOLOGY, 1.0)
        morphology = analysis["morphology"]

        self.assertEqual(morphology["schema"], 3)
        self.assertEqual(
            morphology["sample_columns"],
            ["id", "type", "x", "y", "z", "radius", "parent", "segment"],
        )
        self.assertEqual(len(morphology["samples"]), 7)
        self.assertTrue(all(len(row) == 8 for row in morphology["samples"]))
        self.assertEqual(len(morphology["segments"]), 4)
        self.assertTrue(all(len(row) == 8 for row in morphology["segments"]))
        self.assertEqual(morphology["bounds"], {"min": [0.0, -1.0, 0.0], "max": [3.0, 2.0, 0.0]})

    def test_analysis_cache_reuses_topology_across_sholl_steps(self):
        cache = AnalysisCache(max_entries=2)
        first, first_cached = cache.get_or_analyze(Y_MORPHOLOGY, 1.0)
        second, second_cached = cache.get_or_analyze(Y_MORPHOLOGY, 2.0)
        repeated, repeated_cached = cache.get_or_analyze(Y_MORPHOLOGY, 2.0)

        self.assertFalse(first_cached)
        self.assertFalse(second_cached)
        self.assertTrue(repeated_cached)
        self.assertIs(first.parsed, second.parsed)
        self.assertIs(first.morphology, second.morphology)
        self.assertIs(second, repeated)
        self.assertNotEqual(first.analysis_id, second.analysis_id)

    def test_statistics_survive_full_analysis_eviction_for_cohort_summaries(self):
        cache = AnalysisCache(max_entries=1, max_statistics=3)
        first, _ = cache.get_or_analyze(Y_MORPHOLOGY, 1.0)
        cache.get_or_analyze(UNBRANCHED_MORPHOLOGY, 1.0)

        self.assertIsNone(cache.get(first.analysis_id))
        self.assertIs(cache.get_statistics(first.analysis_id), first.statistics)

    def test_local_api_numeric_options_are_finite_and_seed_is_integral(self):
        self.assertEqual(_optional_number("12.0", integer=True), 12)
        self.assertAlmostEqual(_optional_number("1.25"), 1.25)
        with self.assertRaisesRegex(ValueError, "whole number"):
            _optional_number("1.5", integer=True)
        with self.assertRaisesRegex(ValueError, "finite"):
            _optional_number("nan")
        with self.assertRaisesRegex(ValueError, "true or false"):
            _optional_number(True, integer=True)

    def test_prepared_remodeling_produces_the_exact_seeded_artifact(self):
        request = RemodelRequest(
            file_name="fixture.swc",
            who="random_all",
            random_ratio=50.0,
            action="extend",
            amount=20.0,
            seed=1789,
        )
        direct = remodel_text(Y_MORPHOLOGY, request)
        prepared = remodel_text(
            Y_MORPHOLOGY,
            request,
            parsed=parse_swc_text(Y_MORPHOLOGY),
        )

        self.assertEqual(prepared.content, direct.content)
        self.assertEqual(prepared.targets, direct.targets)
        self.assertIn("# seed: 1789", prepared.content)

    def test_interface_remodel_validation_matches_the_scientific_contract(self):
        invalid = (
            RemodelRequest("fixture.swc", "all_terminal", "none"),
            RemodelRequest(
                "fixture.swc",
                "all_terminal",
                "remove",
                radius_change=10.0,
            ),
            RemodelRequest(
                "fixture.swc",
                "all_terminal",
                "shrink",
                random_ratio=10.0,
                amount=20.0,
            ),
        )
        for request in invalid:
            with self.subTest(request=request), self.assertRaises(ValueError):
                validate_remodel_request(request)

        validate_remodel_request(
            RemodelRequest(
                "fixture.swc",
                "all_terminal",
                "none",
                radius_change=-0.1,
                radius_unit="units",
            )
        )


class CommandLineIntegrationTests(unittest.TestCase):
    def run_cli(self, *arguments: str, expected_status: int = 0):
        completed = subprocess.run(
            [sys.executable, str(REPOSITORY / "remod_cli.py"), *arguments],
            cwd=REPOSITORY,
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(
            completed.returncode,
            expected_status,
            msg=f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}",
        )
        return completed

    def test_analysis_writes_deterministic_single_and_aggregate_json(self):
        with tempfile.TemporaryDirectory() as directory_name:
            directory = Path(directory_name)
            (directory / "a.swc").write_text(Y_MORPHOLOGY, encoding="utf-8")
            (directory / "b.swc").write_text(Y_MORPHOLOGY, encoding="utf-8")
            self.run_cli(
                "analyze",
                str(directory),
                "b.swc,a.swc",
                "--sholl-step",
                "2.5",
            )

            statistics = directory / "downloads" / "statistics"
            results = json.loads((statistics / "results.json").read_text())
            summary = json.loads((statistics / "summary.json").read_text())
            self.assertEqual(list(results), ["a.swc", "b.swc"])
            self.assertEqual(summary["file_count"], 2)
            self.assertEqual(summary["files"], ["a.swc", "b.swc"])
            length = summary["scalar_metrics"]["all_total_length"]
            self.assertAlmostEqual(length["mean"], 4.0 + 2.0 * sqrt(2.0))
            self.assertEqual(length["standard_deviation"], 0.0)

    def test_seeded_edit_is_reproducible_valid_and_reanalyzable(self):
        with tempfile.TemporaryDirectory() as directory_name:
            directory = Path(directory_name)
            source = directory / "fixture.swc"
            source.write_text(Y_MORPHOLOGY, encoding="utf-8")
            output = directory / "branched.swc"
            arguments = (
                "edit",
                "--directory",
                str(directory),
                "--file-name",
                source.name,
                "--output",
                str(output),
                "--who",
                "random_all",
                "--random-ratio",
                "100",
                "--action",
                "branch",
                "--amount",
                "50",
                "--seed",
                "73",
            )
            self.run_cli(*arguments)
            first = output.read_bytes()
            self.run_cli(*arguments, expected_status=1)
            self.run_cli(*arguments, "--force")
            self.assertEqual(output.read_bytes(), first)

            parsed = parse_swc_file(output)
            self.assertEqual(len(parsed.branch_points), 4)
            self.assertEqual(len(parsed.all_terminal), 6)
            identifiers = list(parsed.samples)
            self.assertEqual(identifiers, list(range(1, len(identifiers) + 1)))
            for sample_id, sample in parsed.samples.items():
                parent = int(sample[6])
                self.assertTrue(parent == -1 or parent < sample_id)
            self.assertNotIn(directory_name, output.read_text(encoding="utf-8"))

            self.run_cli(
                "analyze", str(output.parent), output.name, "--sholl-step", "1"
            )

            second_output = directory / "branched_shrunk.swc"
            self.run_cli(
                "edit",
                "--directory",
                str(directory),
                "--file-name",
                output.name,
                "--output",
                str(second_output),
                "--who",
                "all_terminal",
                "--action",
                "shrink",
                "--amount",
                "10",
            )
            self.run_cli("analyze", str(directory), second_output.name)

    def test_invalid_cli_request_fails_without_writing_output(self):
        with tempfile.TemporaryDirectory() as directory_name:
            directory = Path(directory_name)
            source = directory / "fixture.swc"
            source.write_text(Y_MORPHOLOGY, encoding="utf-8")
            self.run_cli(
                "edit",
                "--directory",
                str(directory),
                "--file-name",
                source.name,
                "--who",
                "all_terminal",
                "--action",
                "shrink",
                "--amount",
                "100",
                expected_status=2,
            )
            self.assertFalse((directory / "downloads").exists())

    @unittest.skipUnless(
        importlib.util.find_spec("matplotlib"), "Matplotlib is not installed"
    )
    def test_unbranched_analysis_to_svg_visualization_workflow(self):
        with tempfile.TemporaryDirectory() as directory_name:
            directory = Path(directory_name)
            (directory / "fixture.swc").write_text(
                UNBRANCHED_MORPHOLOGY, encoding="utf-8"
            )
            self.run_cli("analyze", str(directory), "fixture.swc", "--sholl-step", "1")

            results = json.loads(
                (directory / "downloads" / "statistics" / "results.json").read_text()
            )["fixture.swc"]
            self.assertEqual(
                results["sholl_all_branchpoints"],
                {str(bound): 0 for bound in range(1, 6)},
            )

            self.run_cli(
                "edit",
                "--directory",
                str(directory),
                "--file-name",
                "fixture.swc",
                "--who",
                "all_dendrites",
                "--action",
                "remove",
            )
            soma_only = directory / "downloads" / "files" / "fixture_new.swc"
            self.run_cli("analyze", str(soma_only.parent), soma_only.name)

            command = [
                sys.executable,
                str(REPOSITORY / "plot_statistics.py"),
                str(soma_only.parent),
            ]
            completed = subprocess.run(
                command,
                cwd=REPOSITORY,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(completed.returncode, 0, msg=completed.stderr)
            plot_directory = (
                soma_only.parent / "downloads" / "statistics" / "plots" / "aggregate"
            )
            first = {
                path.name: path.read_bytes() for path in plot_directory.glob("*.svg")
            }
            self.assertEqual(len(first), 10)
            self.assertTrue(
                all(content.startswith(b"<?xml") for content in first.values())
            )


class SeededSelectionTests(unittest.TestCase):
    def test_empirical_growth_distribution_is_normalized_and_seedable(self):
        lengths, weights = parse_length_distribution()
        self.assertEqual(len(lengths), 533)
        self.assertEqual(len(weights), len(lengths))
        self.assertAlmostEqual(sum(weights), 1.0)
        first = select_length(lengths, weights, random.Random(91))
        second = select_length(lengths, weights, random.Random(91))
        self.assertEqual(first, second)
        self.assertIn(first, lengths)

    def test_seeded_selection_is_reproducible_uniform_and_without_replacement(self):
        options = list(range(1, 11))
        samples = {root: [[root]] for root in options}
        first, label = sample_random_dendrites(
            options, "all", samples, 0.3, random.Random(123)
        )
        second, _ = sample_random_dendrites(
            options, "all", samples, 0.3, random.Random(123)
        )
        self.assertEqual(first, [1, 2, 5])
        self.assertEqual(second, first)
        self.assertEqual(len(first), len(set(first)))
        self.assertIn("30%", label)

    def test_ratio_rounding_and_validation_are_explicit(self):
        options = [1, 2, 3, 4, 5]
        samples = {root: [[root]] for root in options}
        selected, _ = sample_random_dendrites(
            options, "all", samples, 0.5, random.Random(5)
        )
        self.assertEqual(len(selected), 3)
        self.assertEqual(sample_random_dendrites(options, "all", samples, 0)[0], [])
        self.assertEqual(
            sample_random_dendrites(options, "all", samples, 1, random.Random(1))[0],
            options,
        )
        for invalid in (-0.01, 1.01):
            with self.subTest(ratio=invalid), self.assertRaises(ValueError):
                sample_random_dendrites(options, "all", samples, invalid)


class RemodelingInvariantTests(unittest.TestCase):
    def test_terminal_shrink_is_exact_and_does_not_move_other_samples(self):
        before, after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY, [4], "shrink", 50.0
        )
        self.assertAlmostEqual(after.lengths[4], before.lengths[4] * 0.5)
        self.assertAlmostEqual(
            total_dendritic_length(after),
            total_dendritic_length(before) - before.lengths[4] * 0.5,
        )
        for sample_id in (1, 2, 3, 5, 6, 7):
            self.assertEqual(after.samples[sample_id], before.samples[sample_id])

    def test_shrink_retains_the_crossed_cylindrical_edge_radius(self):
        morphology = """\
1 1 0 0 0 10 -1
2 3 2 0 0 1 1
"""
        _before, after, _lines, _roots, _samples = remodel(
            morphology, [2], "shrink", 50.0
        )
        self.assertAlmostEqual(after.samples[2][5], 1.0)
        self.assertAlmostEqual(after.lengths[2], 1.0)
        self.assertAlmostEqual(sum(after.surface_areas.values()), 2.0 * pi)
        self.assertAlmostEqual(total_dendritic_volume(after), pi)

    def test_nonterminal_shrink_translates_descendants_rigidly(self):
        before, after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY, [2], "shrink", 25.0
        )
        self.assertAlmostEqual(after.lengths[2], 1.5)
        self.assertAlmostEqual(after.lengths[4], before.lengths[4])
        self.assertAlmostEqual(after.lengths[5], before.lengths[5])
        for child in (4, 5):
            before_vector = np.asarray(before.samples[child][2:5]) - np.asarray(
                before.samples[3][2:5]
            )
            after_vector = np.asarray(after.samples[child][2:5]) - np.asarray(
                after.samples[3][2:5]
            )
            np.testing.assert_allclose(after_vector, before_vector)

    def test_remove_deletes_the_complete_subtree_without_orphans(self):
        _before, after, _lines, _roots, _samples = remodel(Y_MORPHOLOGY, [2], "remove")
        self.assertEqual(set(after.samples), {1, 6, 7})
        self.assertEqual(after.dendrite_roots, [6])
        self.assertEqual(after.all_terminal, [6])
        for sample in after.samples.values():
            self.assertTrue(int(sample[6]) == -1 or int(sample[6]) in after.samples)

    def test_nonterminal_extend_adds_exact_length_and_preserves_distal_geometry(self):
        before, after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY, [2], "extend", 1.0, "units", seed=31
        )
        self.assertAlmostEqual(
            total_dendritic_length(after), total_dendritic_length(before) + 1.0
        )
        self.assertAlmostEqual(after.lengths[2], before.lengths[2] + 1.0)
        self.assertAlmostEqual(after.lengths[4], before.lengths[4])
        self.assertAlmostEqual(after.lengths[5], before.lengths[5])
        new_ids = set(after.samples) - set(before.samples)
        self.assertTrue(new_ids)
        self.assertTrue(new_ids.issubset(segment_sample_ids(after)[2]))
        soma = np.asarray(after.soma_samples[0][2:5], dtype=float)
        generated = [
            sample
            for sample in after.segments[2]
            if int(sample[0]) in new_ids
        ]
        radial_distances = [
            np.linalg.norm(np.asarray(before.samples[3][2:5], dtype=float) - soma),
            *[
                np.linalg.norm(np.asarray(sample[2:5], dtype=float) - soma)
                for sample in generated
            ],
        ]
        self.assertTrue(
            all(
                distal >= proximal
                for proximal, distal in zip(radial_distances, radial_distances[1:])
            )
        )
        new_tip = int(after.samples[4][6])
        self.assertIn(new_tip, new_ids)
        self.assertEqual(int(after.samples[4][6]), new_tip)
        self.assertEqual(int(after.samples[5][6]), new_tip)

    def test_branch_adds_two_daughters_of_the_requested_length(self):
        before, after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY, [4], "branch", 50.0, seed=41
        )
        target_length = before.lengths[4] * 0.5
        daughters = sorted(
            sample_id
            for sample_id, sample in after.samples.items()
            if int(sample[6]) == 4
        )
        self.assertEqual(len(daughters), 2)
        self.assertEqual(len(after.branch_points), len(before.branch_points) + 1)
        self.assertEqual(len(after.dendrite_roots), len(before.dendrite_roots) + 2)
        self.assertEqual(len(after.all_terminal), len(before.all_terminal) + 1)
        for daughter in daughters:
            self.assertAlmostEqual(after.lengths[daughter], target_length)
            radii = [
                np.linalg.norm(np.asarray(before.samples[4][2:5], dtype=float)),
                *[
                    np.linalg.norm(np.asarray(sample[2:5], dtype=float))
                    for sample in after.segments[daughter]
                ],
            ]
            self.assertTrue(
                all(
                    distal >= proximal
                    for proximal, distal in zip(radii, radii[1:])
                )
            )
        self.assertAlmostEqual(
            total_dendritic_length(after),
            total_dendritic_length(before) + 2.0 * target_length,
        )

    def test_branch_daughters_inherit_the_changed_attachment_radius(self):
        result = remodel_text(
            Y_MORPHOLOGY,
            RemodelRequest(
                file_name="fixture.swc",
                who="manual",
                manual_segments="4",
                action="branch",
                amount=50.0,
                radius_change=50.0,
                seed=41,
            ),
        )
        parsed = result.parsed
        new_branch = max(parsed.branch_points)
        daughters = [
            root
            for root in parsed.dendrite_roots
            if int(parsed.segments[root][0][6]) == new_branch
        ]

        self.assertEqual(len(daughters), 2)
        self.assertAlmostEqual(parsed.samples[new_branch][5], 0.75)
        for daughter in daughters:
            self.assertAlmostEqual(
                parsed.segments[daughter][0][5],
                parsed.samples[new_branch][5],
            )

    def test_tiny_representable_extension_is_not_silently_ignored(self):
        before, after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY, [4], "extend", 1e-11, "units", seed=43
        )
        added = total_dendritic_length(after) - total_dendritic_length(before)
        self.assertAlmostEqual(added, 1e-11, delta=1e-13)

    def test_scale_changes_all_selected_linear_dimensions_by_one_factor(self):
        before = parse_text(Y_MORPHOLOGY)
        before_roots = list(before.dendrite_roots)
        _before, after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY, before_roots, "scale", 200.0
        )
        self.assertAlmostEqual(
            total_dendritic_length(after), 2.0 * total_dendritic_length(before)
        )
        self.assertAlmostEqual(
            sum(after.surface_areas.values()), 4.0 * sum(before.surface_areas.values())
        )
        self.assertAlmostEqual(
            total_dendritic_volume(after), 8.0 * total_dendritic_volume(before)
        )
        for root in before_roots:
            self.assertAlmostEqual(after.lengths[root], 2.0 * before.lengths[root])
        for sample_id, sample in before.samples.items():
            if int(sample[1]) in {3, 4}:
                np.testing.assert_allclose(
                    after.samples[sample_id][2:5],
                    2.0 * np.asarray(sample[2:5], dtype=float),
                )
                self.assertAlmostEqual(after.samples[sample_id][5], 2.0 * sample[5])
        self.assertEqual(after.samples[1], before.samples[1])

    def test_scale_can_target_one_region_without_changing_the_other(self):
        before = parse_text(Y_MORPHOLOGY)
        _before, after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY, before.basal, "scale", 150.0
        )
        for root in before.basal:
            self.assertAlmostEqual(after.lengths[root], 1.5 * before.lengths[root])
        for root in before.apical:
            self.assertAlmostEqual(after.lengths[root], before.lengths[root])
            for sample_id in segment_sample_ids(before)[root]:
                self.assertEqual(after.samples[sample_id], before.samples[sample_id])

    def test_radius_change_supports_percent_and_absolute_units(self):
        before, percent_after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY,
            [4],
            "none",
            radius_change=50.0,
            radius_unit="percent",
        )
        self.assertAlmostEqual(percent_after.samples[4][5], 0.75)
        self.assertEqual(percent_after.samples[5], before.samples[5])

        _before, absolute_after, _lines, _roots, _samples = remodel(
            Y_MORPHOLOGY,
            [4],
            "none",
            radius_change=-0.1,
            radius_unit="units",
        )
        self.assertAlmostEqual(absolute_after.samples[4][5], 0.4)

        high_offset = """\
1 1 100000000000000 0 0 1 -1
2 3 100000000000000.25 0 0 0.5 1
"""
        high_before, high_after, _lines, _roots, _samples = remodel(
            high_offset,
            [2],
            "none",
            radius_change=10.0,
        )
        self.assertEqual(
            high_after.samples[2][2:5],
            high_before.samples[2][2:5],
        )

    def test_invalid_actions_fail_instead_of_emitting_invalid_geometry(self):
        with self.assertRaisesRegex(ValueError, "entire segment"):
            remodel(Y_MORPHOLOGY, [4], "shrink", 100.0)
        with self.assertRaisesRegex(ValueError, "non-positive radius"):
            remodel(
                Y_MORPHOLOGY,
                [4],
                "none",
                radius_change=-0.5,
                radius_unit="units",
            )
        with self.assertRaisesRegex(ValueError, "more than 100000 samples"):
            remodel(
                Y_MORPHOLOGY,
                [4],
                "extend",
                1e20,
                "units",
            )
        inward = """\
1 1 0 0 0 1 -1
2 3 10 0 0 0.5 1
3 3 9 0 0 0.5 2
"""
        with self.assertRaisesRegex(ValueError, "outward from the soma"):
            remodel(inward, [2], "extend", 1.0, "units")

        high_offset = """\
1 1 10000000000000000 0 0 1 -1
2 3 10000000000000002 0 0 0.5 1
"""
        with self.assertRaisesRegex(ValueError, "shrink is not representable"):
            remodel(high_offset, [2], "shrink", 50.0)
        with self.assertRaisesRegex(ValueError, "scale is not representable"):
            remodel(high_offset, [2], "scale", 1e-10)

        overflowing = """\
1 1 0 0 0 1 -1
2 3 1e200 0 0 0.5 1
"""
        with self.assertRaisesRegex(ValueError, "scale exceeds finite numeric range"):
            remodel(overflowing, [2], "scale", 1e200)


if __name__ == "__main__":
    unittest.main()
